custom:
    rest:
        readTimeout: 120000
        connectionTimeout: 120000

spring.session.store-type: redis

feign.hystrix.enabled: true
spring.cloud.loadbalancer.retry.enabled: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 120000
ribbon.ReadTimeout: 180000
ribbon.ConnectTimeout: 180000
management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,env,bus-refresh,hystrix.stream