config:
    client:
        test: word33

spring:
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://localhost:9998/
  sleuth:
    sampler:
      probability: 1.0
   